enum Genre {
  g00s,
  g40s,
  g50s,
  g60s,
  g70s,
  g80s,
  g90s,
  gAC,
  gAcid,
  gAcoustic,
  gAcousticRock,
  gActiveRock,
  gAdultRock,
  gAffairs,
  gAfrican,
  gAlQuran,
  gAlternative,
  gAlternativeRock,
  gAnime,
  gArabic,
  gArt,
  gArtist,
  gAsian,
  gBachata,
  gBallade,
  gBass,
  gBigBand,
  gBlues,
  gBollywood,
  gBossaNova,
  gBusiness,
  gCaribbean,
  gCeltic,
  gChildren,
  gChristian,
  gChristmas,
  gClassicRock,
  gClassical,
  gClub,
  gCollege,
  gComedy,
  gCommunity,
  gContemporary,
  gCountry,
  gCulture,
  gCumbia,
  gCurrentAffairs,
  gDance,
  gDancehall,
  gDeepHouse,
  gDisco,
  gDJ,
  gDnB,
  gDowntempo,
  gDrumandBass,
  gDubstep,
  gEasyListening,
  gEclectic,
  gEDM,
  gEducation,
  gElectro,
  gEntertainment,
  gEthnic,
  gEuro,
  gEvents,
  gFilm,
  gFlamenco,
  gFolk,
  gFunk,
  gGay,
  gGospel,
  gGothic,
  gGroove,
  gHardRock,
  gHardcore,
  gHealth,
  gHeavyMetal,
  gHipHop,
  gHits,
  gHotAC,
  gHouse,
  gIndie,
  gInformation,
  gInstrumental,
  gInternationalNews,
  gIslamic,
  gItalian,
  gJazz,
  gJazzRock,
  gJpopKpop,
  gKizomba,
  gLatin,
  gLatinJazz,
  gLightRock,
  gLocal,
  gLocalNews,
  gLounge,
  gLove,
  gLoveSongs,
  gMelodic,
  gMelody,
  gMental,
  gMerengue,
  gMetal,
  gMetalRock,
  gMinimal,
  gMix,
  gModernRock,
  gMusic,
  gNationalNews,
  gNewAge,
  gNews,
  gOldSchool,
  gOldies,
  gOriental,
  gParty,
  gPoliticalNews,
  gPolitics,
  gPop,
  gPopLatino,
  gProgressive,
  gPublic,
  gPunk,
  gRamadan,
  gRap,
  gReggae,
  gReggaeton,
  gRegional,
  gReligious,
  gRemix,
  gRetro,
  gRhythmic,
  gRnB,
  gRock,
  gRockClassics,
  gRomance,
  gRomantic,
  gRumba,
  gSalsa,
  gSmoothJazz,
  gSoca,
  gSoft,
  gSongs,
  gSoul,
  gSoundtrack,
  gSpanish,
  gSpoken,
  gSport,
  gSportsNews,
  gSportsTalk,
  gSwing,
  gTalk,
  gTamil,
  gTango,
  gTechno,
  gTeenPop,
  gTop40,
  gTraffic,
  gTrance,
  gTropical,
  gTurkish,
  gUrban,
  gVariety,
  gWorld,
  gYouthprogramming,
  gZouk,
  gZumba
}

var allGenres = {
  1: Genre.g00s,
  2: Genre.g40s,
  3: Genre.g50s,
  4: Genre.g60s,
  5: Genre.g70s,
  6: Genre.g80s,
  7: Genre.g90s,
  8: Genre.gAC,
  9: Genre.gAcid,
  10: Genre.gAcoustic,
  11: Genre.gAcousticRock,
  12: Genre.gActiveRock,
  14: Genre.gAdultRock,
  15: Genre.gAffairs,
  16: Genre.gAfrican,
  17: Genre.gAlQuran,
  18: Genre.gAlternative,
  19: Genre.gAlternativeRock,
  21: Genre.gAnime,
  22: Genre.gArabic,
  23: Genre.gArt,
  24: Genre.gArtist,
  25: Genre.gAsian,
  26: Genre.gBachata,
  27: Genre.gBallade,
  28: Genre.gBass,
  29: Genre.gBigBand,
  30: Genre.gBlues,
  31: Genre.gBollywood,
  32: Genre.gBossaNova,
  33: Genre.gBusiness,
  35: Genre.gCaribbean,
  36: Genre.gCeltic,
  37: Genre.gChildren,
  39: Genre.gChristian,
  40: Genre.gChristmas,
  45: Genre.gClassicRock,
  44: Genre.gClassical,
  46: Genre.gClub,
  47: Genre.gCollege,
  48: Genre.gComedy,
  49: Genre.gCommunity,
  50: Genre.gContemporary,
  51: Genre.gCountry,
  52: Genre.gCulture,
  53: Genre.gCumbia,
  54: Genre.gCurrentAffairs,
  55: Genre.gDance,
  56: Genre.gDancehall,
  57: Genre.gDeepHouse,
  58: Genre.gDisco,
  59: Genre.gDJ,
  60: Genre.gDnB,
  61: Genre.gDowntempo,
  62: Genre.gDrumandBass,
  63: Genre.gDubstep,
  65: Genre.gEasyListening,
  66: Genre.gEclectic,
  68: Genre.gEDM,
  69: Genre.gEducation,
  70: Genre.gElectro,
  71: Genre.gEntertainment,
  72: Genre.gEthnic,
  73: Genre.gEuro,
  74: Genre.gEvents,
  75: Genre.gFilm,
  76: Genre.gFlamenco,
  77: Genre.gFolk,
  79: Genre.gFunk,
  81: Genre.gGay,
  82: Genre.gGospel,
  83: Genre.gGothic,
  85: Genre.gGroove,
  87: Genre.gHardRock,
  88: Genre.gHardcore,
  89: Genre.gHealth,
  90: Genre.gHeavyMetal,
  92: Genre.gHipHop,
  93: Genre.gHits,
  95: Genre.gHotAC,
  96: Genre.gHouse,
  98: Genre.gIndie,
  99: Genre.gInformation,
  100: Genre.gInstrumental,
  101: Genre.gInternationalNews,
  103: Genre.gIslamic,
  104: Genre.gItalian,
  105: Genre.gJazz,
  106: Genre.gJazzRock,
  107: Genre.gJpopKpop,
  109: Genre.gKizomba,
  110: Genre.gLatin,
  111: Genre.gLatinJazz,
  112: Genre.gLightRock,
  113: Genre.gLocal,
  114: Genre.gLocalNews,
  115: Genre.gLounge,
  116: Genre.gLove,
  117: Genre.gLoveSongs,
  118: Genre.gMelodic,
  119: Genre.gMelody,
  120: Genre.gMental,
  121: Genre.gMerengue,
  122: Genre.gMetal,
  123: Genre.gMetalRock,
  124: Genre.gMinimal,
  125: Genre.gMix,
  127: Genre.gModernRock,
  128: Genre.gMusic,
  130: Genre.gNationalNews,
  131: Genre.gNewAge,
  132: Genre.gNews,
  133: Genre.gOldSchool,
  134: Genre.gOldies,
  136: Genre.gOriental,
  137: Genre.gParty,
  139: Genre.gPoliticalNews,
  140: Genre.gPolitics,
  141: Genre.gPop,
  142: Genre.gPopLatino,
  143: Genre.gProgressive,
  145: Genre.gPublic,
  147: Genre.gPunk,
  148: Genre.gRamadan,
  149: Genre.gRap,
  150: Genre.gReggae,
  151: Genre.gReggaeton,
  152: Genre.gRegional,
  153: Genre.gReligious,
  154: Genre.gRemix,
  155: Genre.gRetro,
  162: Genre.gRhythmic,
  156: Genre.gRnB,
  157: Genre.gRock,
  158: Genre.gRockClassics,
  159: Genre.gRomance,
  160: Genre.gRomantic,
  161: Genre.gRumba,
  163: Genre.gSalsa,
  166: Genre.gSmoothJazz,
  167: Genre.gSoca,
  168: Genre.gSoft,
  169: Genre.gSongs,
  170: Genre.gSoul,
  171: Genre.gSoundtrack,
  172: Genre.gSpanish,
  173: Genre.gSpoken,
  174: Genre.gSport,
  175: Genre.gSportsNews,
  176: Genre.gSportsTalk,
  178: Genre.gSwing,
  179: Genre.gTalk,
  180: Genre.gTamil,
  181: Genre.gTango,
  182: Genre.gTechno,
  183: Genre.gTeenPop,
  184: Genre.gTop40,
  185: Genre.gTraffic,
  186: Genre.gTrance,
  189: Genre.gTropical,
  190: Genre.gTurkish,
  192: Genre.gUrban,
  193: Genre.gVariety,
  194: Genre.gWorld,
  195: Genre.gYouthprogramming,
  196: Genre.gZouk,
  197: Genre.gZumba,
};

extension GenreExt on Genre {
  String get id {
    return allGenres.keys.firstWhere((k) => allGenres[k] == this).toString();
  }
}
