// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'station.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Station _$StationFromJson(Map<String, dynamic> json) => Station(
      id: json['i'] as String,
      name: json['name'] as String,
      genre: Serialization.genreFromString(json['d'] as String),
      country: $enumDecode(_$CountryEnumMap, json['c']),
      logoUrl: json['l'] as String,
      streamURl: json['u'] as String,
    );

Map<String, dynamic> _$StationToJson(Station instance) => <String, dynamic>{
      'i': instance.id,
      'name': instance.name,
      'd': Serialization.stringIdFromGenre(instance.genre),
      'c': _$CountryEnumMap[instance.country]!,
      'l': instance.logoUrl,
      'u': instance.streamURl,
    };

const _$CountryEnumMap = {
  Country.AF: 'AF',
  Country.AD: 'AD',
  Country.AE: 'AE',
  Country.AG: 'AG',
  Country.AL: 'AL',
  Country.AM: 'AM',
  Country.AO: 'AO',
  Country.AR: 'AR',
  Country.AT: 'AT',
  Country.AU: 'AU',
  Country.AW: 'AW',
  Country.AZ: 'AZ',
  Country.BA: 'BA',
  Country.BD: 'BD',
  Country.BE: 'BE',
  Country.BG: 'BG',
  Country.BI: 'BI',
  Country.BJ: 'BJ',
  Country.BM: 'BM',
  Country.BO: 'BO',
  Country.BR: 'BR',
  Country.BS: 'BS',
  Country.BW: 'BW',
  Country.BY: 'BY',
  Country.CA: 'CA',
  Country.CG: 'CG',
  Country.CH: 'CH',
  Country.CI: 'CI',
  Country.CL: 'CL',
  Country.CM: 'CM',
  Country.CO: 'CO',
  Country.CR: 'CR',
  Country.CW: 'CW',
  Country.CY: 'CY',
  Country.CZ: 'CZ',
  Country.DE: 'DE',
  Country.DK: 'DK',
  Country.DM: 'DM',
  Country.DO: 'DO',
  Country.DZ: 'DZ',
  Country.EC: 'EC',
  Country.EE: 'EE',
  Country.EG: 'EG',
  Country.ES: 'ES',
  Country.ET: 'ET',
  Country.FI: 'FI',
  Country.FJ: 'FJ',
  Country.FR: 'FR',
  Country.GD: 'GD',
  Country.GH: 'GH',
  Country.GR: 'GR',
  Country.GT: 'GT',
  Country.GY: 'GY',
  Country.HK: 'HK',
  Country.HN: 'HN',
  Country.HR: 'HR',
  Country.HT: 'HT',
  Country.HU: 'HU',
  Country.ID: 'ID',
  Country.IE: 'IE',
  Country.IL: 'IL',
  Country.IN: 'IN',
  Country.IQ: 'IQ',
  Country.IR: 'IR',
  Country.IS: 'IS',
  Country.IT: 'IT',
  Country.JM: 'JM',
  Country.JO: 'JO',
  Country.JP: 'JP',
  Country.KE: 'KE',
  Country.KR: 'KR',
  Country.LB: 'LB',
  Country.LC: 'LC',
  Country.LI: 'LI',
  Country.LK: 'LK',
  Country.LT: 'LT',
  Country.LU: 'LU',
  Country.LV: 'LV',
  Country.LY: 'LY',
  Country.MA: 'MA',
  Country.MG: 'MG',
  Country.MK: 'MK',
  Country.ML: 'ML',
  Country.MT: 'MT',
  Country.MU: 'MU',
  Country.MX: 'MX',
  Country.MY: 'MY',
  Country.NA: 'NA',
  Country.NG: 'NG',
  Country.NI: 'NI',
  Country.NL: 'NL',
  Country.NO: 'NO',
  Country.NP: 'NP',
  Country.NZ: 'NZ',
  Country.OM: 'OM',
  Country.PA: 'PA',
  Country.PE: 'PE',
  Country.PH: 'PH',
  Country.PK: 'PK',
  Country.PL: 'PL',
  Country.PS: 'PS',
  Country.PT: 'PT',
  Country.PY: 'PY',
  Country.RO: 'RO',
  Country.RS: 'RS',
  Country.RU: 'RU',
  Country.SA: 'SA',
  Country.SD: 'SD',
  Country.SE: 'SE',
  Country.SG: 'SG',
  Country.SI: 'SI',
  Country.SK: 'SK',
  Country.SL: 'SL',
  Country.SM: 'SM',
  Country.SN: 'SN',
  Country.SR: 'SR',
  Country.SV: 'SV',
  Country.SY: 'SY',
  Country.TG: 'TG',
  Country.TH: 'TH',
  Country.TN: 'TN',
  Country.TR: 'TR',
  Country.TT: 'TT',
  Country.TZ: 'TZ',
  Country.UA: 'UA',
  Country.UG: 'UG',
  Country.UK: 'UK',
  Country.US: 'US',
  Country.UY: 'UY',
  Country.VC: 'VC',
  Country.VE: 'VE',
  Country.VN: 'VN',
  Country.ZA: 'ZA',
  Country.ZW: 'ZW',
};
