name: radio_upp
description: Online radio app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  bloc: 8.1.0
  cupertino_icons: 1.0.2
  dio: 4.0.6
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_config: 2.0.0
  get_it: 7.2.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  json_annotation: 4.7.0
  provider: 6.0.4

dev_dependencies:
  build_runner: 2.3.2
  flutter_launcher_icons: 0.11.0
  flutter_lints: 2.0.0
  flutter_native_splash: 2.2.16
  flutter_test:
    sdk: flutter
  json_serializable: 6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/genres
  fonts:
    - family: Bossa
      fonts:
        - asset: assets/fonts/bossa/Bossa-Black.otf
          weight: 900
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 700

