name: radio_upp
description: Online radio app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  audio_session: ^0.1.11
  auto_animated: 3.1.0
  auto_size_text: 3.0.0
  bloc: 8.1.0
  cached_network_image: 3.2.3
  change_case: 1.0.2
  cupertino_icons: 1.0.2
  dart_ipify: 1.1.1
  dio: 4.0.6
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_config: 2.0.0
  get_it: 7.2.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  infinite_listview: 1.1.0
  json_annotation: 4.7.0
  just_audio: 0.9.30
  pretty_dio_logger: 1.2.0-beta-1
  provider: 6.0.4
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: 2.3.2
  flutter_launcher_icons: 0.11.0
  flutter_lints: 2.0.0
  flutter_native_splash: 2.2.16
  flutter_test:
    sdk: flutter
  json_serializable: 6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/genres/
  fonts:
    - family: Bossa
      fonts:
        - asset: assets/fonts/bossa/Bossa-Black.otf
          weight: 900
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 700
    - family: BrandIcons
      fonts:
        - asset: assets/fonts/brand_icons/BrandIcons.ttf
